# Hyperparameters

prediction_horizon: 16
observation_horizon: 2
action_horizon: 8
batch_size: 16
num_workers: 8
learning_rate: 0.0001
weight_decay: 0.001
num_warmup_steps: 600
epochs: 1500
num_diffusion_iters: 100

use_pretrained_model: True
model_path: "model/tablecleaner.pt"
dataset_path: "table_cleaner.zarr"

device: "cuda"
wandb_project: "table_cleaner"
